Create setup_dev_machine
added condition to exit upon ansible-playbook failing

diff --git a/bin/setup_dev_machine b/bin/setup_dev_machine
--- a/bin/setup_dev_machine
+++ b/bin/setup_dev_machine
@@ -160,6 +160,10 @@ echo " -------------------"
 echo ""
 
 ansible-playbook -vvv -K sr-build-tools/ansible/vagrant_site.yml --extra-vars "config_branch=${SR_CONFIG_BRANCH} ros_user=`whoami` ros_workspace=${WORKSPACE_PATH} ros_group=`whoami` ros_workspace_install=${ROSINSTALL_PATH} github_login=${GITHUB_LOGIN} github_password=${GITHUB_PASSWORD}"
+if [ $? -ne 0 ]; then
+  echo "Ansible playbook failed!"
+  exit 1
+fi
 
 echo ""
 echo " ------------------------------------------------"
