Delete jobs with no branch.

diff --git a/bin/sr-jenkins-git-remote-add b/bin/sr-jenkins-git-remote-add
--- a/bin/sr-jenkins-git-remote-add
+++ b/bin/sr-jenkins-git-remote-add
@@ -2,9 +2,12 @@
 
 #
 # Quick and dirty script to scan a remote repo for branches and add jobs to
-# jenkins for them.
+# jenkins for them. Deletes jobs with no matching branches.
 #
-# Filters branches to F_* only
+# We only act on jobs that start with the job_prefix below. This is important
+# when deleting, using a bad prefix might cause havoc on jenkins!
+#
+# Filters branches to F_* only.
 #
 # Probably contains assuptions for ronex (the label used) but should be pretty
 # generic. Just needs a few more args.
@@ -32,6 +35,7 @@ job_labels="slave-ronex"
 job_schedule="H/5 * * * *"
 job_command="/opt/shadow/sr-build-tools/bin/sr-jenkins-catkin hydro"
 jenkins_cmd="sr-jenkins-jobs -j jenkins:8080"
+tmp_github_job_list="/tmp/$(basename $0)-github-jobs"
 
 while getopts "hn" opt; do
     case $opt in
@@ -57,13 +61,19 @@ REPO=$1
 # Main
 #
 
+branch_to_name() {
+    branch="$1"
+    echo "$job_prefix$(basename $REPO .git)-$branch"
+}
 
 add_branch() {
     [ -n "$1" ] || { echo No branch!; return 10; }
     branch=$1
-    name="$(basename $REPO .git)-$branch"
+    #name="$(basename $REPO .git)-$branch"
+    name=$(branch_to_name "$branch")
+    #name="$prefix$name"
     # Add the job skipping errors for already exists
-    $jenkins_cmd add --prefix "$job_prefix" \
+    $jenkins_cmd add \
         --name $name \
         --labels "$job_labels" \
         --git_source="$REPO" \
@@ -73,15 +83,38 @@ add_branch() {
         --command="$job_command" \
         --enable \
         2>/dev/null || return 0
-    name="$prefix$name"
-    echo Added job name $name
+    echo Added job name $name for $branch
     $jenkins_cmd build $name
 }
 
+# Find branches from github, adding jobs for them. Make a list of the jenkins
+# job names for those braches
+cat /dev/null > $tmp_github_job_list
 for branch in $(git ls-remote --heads git@github.com:shadow-robot/sr-ronex-dev.git | cut -f2 | sed 's/refs\/heads\///' | grep -i '^F_'); do
-    if [ $dry_run ]; then
+    name=$(branch_to_name "$branch")
+    if [ -z "$dry_run" ]; then
         add_branch $branch
     else
-        echo Add $branch
+        echo Add $branch as $name
     fi
+    echo "$name" >> $tmp_github_job_list
 done;
+
+# Delete jobs for branches that don't exist anymore
+# Only consider jobs that start with out prefix so we don't trash jenkins!
+for job in $(bin/sr-jenkins-jobs -j jenkins:8080 list "^$job_prefix" | sed 's/^.* - //')
+do
+    if ! grep -q "$job" $tmp_github_job_list; then
+        # Job in jenkins but not branch on github
+        if [ -z "$dry_run" ]; then
+            $jenkins_cmd rm "$job"
+        else
+            echo Delete job $job
+        fi
+    fi
+done
+        
+# Cleanup
+if [ -z "$dry_run" ]; then
+    rm "$tmp_github_job_list"
+fi
